CREATE DATABASE QL_KhachSan
GO


-- Sử dụng Database vừa tạo
USE QL_KhachSan
GO

CREATE TABLE NhanVien
(
	maNV TINYINT IDENTITY(1,1) PRIMARY KEY,
	taikhoan VARCHAR(50) UNIQUE NOT NULL,
	matkhau VARCHAR(10) UNIQUE NOT NULL,
	tenNV NVARCHAR(30),
	ca VARCHAR(MAX),
	dangnhapgannhat DATETIME,
	luong DECIMAL(12,3) DEFAULT 0,
)
GO

CREATE TABLE KhachHang
(
	cmt VARCHAR(20) PRIMARY KEY,
	taikhoan VARCHAR(50),
	matkhau VARCHAR(10),
	tenKH NVARCHAR(30),
	sdt VARCHAR(11),
	email VARCHAR(50),
	ngaytao DATE,
	solangiaodich INT,
)
GO



CREATE TABLE DichVu
(
	loaiDV NVARCHAR(20) PRIMARY KEY
)
GO

ALTER TABLE DichVu
ADD CONSTRAINT C_LOAIDV_DICHVU		CHECK (loaiDV IN (N'theo giờ', N'theo ngày', N'theo tháng', N'quá giờ'))
GO

CREATE TABLE DichVuChung
(
	maDVC INT IDENTITY(1,1) PRIMARY KEY,
	tenDVC NVARCHAR(500),
	giaDVC DECIMAL(10,3) DEFAULT 1,
	donvitinhDVC NVARCHAR(500),
	trangthaiDVC BIT,
)
GO

CREATE TABLE Phong
(
	maphong TINYINT IDENTITY(1,1) PRIMARY KEY,
	lau TINYINT,
	trangthai NVARCHAR(20),
	tenLP NVARCHAR(20),
	songuoi TINYINT DEFAULT 1,	
)
GO


ALTER TABLE Phong
ADD CONSTRAINT C_TENLP_PHONG		CHECK (tenLP IN (N'phòng đơn', N'phòng đôi'))
GO

ALTER TABLE Phong
ADD CONSTRAINT C_TRANGTHAI_PHONG		CHECK (trangthai IN(N'trống', N'đầy', N'đã đặt trước'))
GO

CREATE TABLE GiaPhong
(
	gia DECIMAL(10,3) DEFAULT 1,
	--khoa ngoai
	loaiDV NVARCHAR(20),
	maphong TINYINT,
	

	CONSTRAINT PK_GIAPHONG PRIMARY KEY(loaiDV, maphong),
	CONSTRAINT FK_GIAPHONG_DICHVU FOREIGN KEY(loaiDV) REFERENCES DichVu(loaiDV),
	CONSTRAINT FK_GIAPHONG_PHONG FOREIGN KEY(maphong) REFERENCES Phong(maphong)
)
GO

CREATE TABLE PhieuChi
(
	maPC INT IDENTITY(1,1) PRIMARY KEY,
	diengiai NTEXT,
	mucchi NVARCHAR(100),
	tongtien DECIMAL(15,3) DEFAULT 0,
	ngaytao DATETIME NOT NULL,
	-- khóa ngoại
	maNV TINYINT NOT NULL,

	CONSTRAINT FK_PHIEUCHI_NHANVIEN		FOREIGN KEY(maNV)	 REFERENCES NhanVien(maNV)
)
GO

ALTER TABLE PhieuChi
ADD CONSTRAINT C_MUCCHI_PHIEUCHI		CHECK (mucchi IN (N'tiền điện', N'tiền nước', N'tiền internet', N'tiền trả khách', N'tiền vệ sinh',N'tiền sửa chữa', N'tiền tiếp khách', N'tiền nhập kho', N'tiền chi khác' ))
GO

CREATE TABLE PhieuThu
(
	maPT INT IDENTITY(1,1) PRIMARY KEY,
	ngaytao DATETIME NOT NULL,
	thoigianvao DATETIME,
	thoigianra DATETIME,
	khuyenmai  DECIMAL(15,3) DEFAULT 0,
	tratruoc DECIMAL(15,3) DEFAULT 0,
	tongtien DECIMAL(15,3) DEFAULT 0,
	hinhthucTT NVARCHAR(100),
	trangthaiTT BIT,
	soluong INT,
	
	-- khóa ngoại
	maNV TINYINT NOT NULL,
	maphong TINYINT NOT NULL,
	loaiDV NVARCHAR(20) NOT NULL,
	cmt VARCHAR(20) NOT NULL,	

	CONSTRAINT FK_PHIEUTHU_NHANVIEN			FOREIGN KEY(maNV)			REFERENCES NhanVien(maNV),
	CONSTRAINT FK_PHIEUTHU_PHONG			FOREIGN KEY(maphong)		REFERENCES Phong(maphong),
	CONSTRAINT FK_PHIEUTHU_DICHVU			FOREIGN KEY(loaiDV)			REFERENCES DichVu(loaiDV),
	CONSTRAINT FK_PHIEUTHU_KHACHHANG		FOREIGN KEY(cmt)			REFERENCES KhachHang(cmt)
)
GO

ALTER TABLE PhieuThu
ADD CONSTRAINT C_HINHTHUCTT_PHIEUCHI		CHECK (hinhthucTT IN (N'tiền mặt', N'thẻ tín dụng', N'thẻ ATM'))
GO

CREATE TABLE PhieuThu_DichVuChung
(	
	soluong INT DEFAULT 0,
	hethan DATETIME,
	tongtienDVC DECIMAL(15,3) DEFAULT 0,
	--Khoa ngoai
	maPT INT UNIQUE,
	maDVC INT UNIQUE,

	CONSTRAINT PK_PHIEUTHU_DICHVUCHUNG PRIMARY KEY(maPT, maDVC),
	CONSTRAINT FK_PHIEUTHU_DICHVUCHUNG_DICHVUCHUNG FOREIGN KEY(maDVC) REFERENCES DichVuChung(maDVC),
	CONSTRAINT FK_PHIEUTHU_DICHVUCHUNG_PHIEUTHU FOREIGN KEY(maPT) REFERENCES PhieuThu(maPT)
)

