CREATE DATABASE QuanLy_HS_GV_THPT
GO

USE QuanLy_HS_GV_THPT
GO

--------------------TẠO KHÓA CHÍNH VÀ CÁC BẢNG-----------------

CREATE TABLE HOCSINH
(
	MaHS VARCHAR(10) PRIMARY KEY,
	HoTenHS NVARCHAR(50),
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam',N'Nữ')),
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	SDT VARCHAR(10) , -- sdt phụ huynh 
	MaLT VARCHAR(10), --Lớp Trưởng
	MaBT VARCHAR(10), --Bí Thư
	HanhKiem VARCHAR(10),
	NienKhoa VARCHAR(10),
	DanToc NVARCHAR(20),
	TonGiao NVARCHAR(50),
	MaLop VARCHAR(10)
);

CREATE TABLE DIEM
(
	DiemSo FLOAT ,
	LoaiDiem NVARCHAR(50) ,
	NamHoc VARCHAR(20) ,
	HocKy VARCHAR(10) CHECK (HocKy IN (N'Học Kỳ I' , N'Học Kỳ II')) ,
	MaHS VARCHAR(10),
	MaMH VARCHAR(10)

	CONSTRAINT PK_DIEM PRIMARY KEY(MaHS,MaGV)
);

CREATE TABLE MONHOC
(
	MaMH VARCHAR(10) PRIMARY KEY,
	TenMH NVARCHAR(30) ,
	KhoiMH VARCHAR(5) 
);

CREATE TABLE GIAOVIEN
(
	MaGV VARCHAR(10) PRIMARY KEY ,
	HoTenGV NVARCHAR(50) ,
	GioiTinh NVARCHAR(3) CHECK (GioiTinh IN ('Nam',N'Nữ')),
	NgaySinh DATE ,
	DiaChi NVARCHAR(100) , 
	SDT VARCHAR(10) ,
	Luong INT,
	PhongBan nvarchar(50),
	MaHT VARCHAR(10) , --- hiệu trưởng
	MaMH varchar(10)
);

CREATE TABLE LOP
(
	MaLop VARCHAR(10) PRIMARY KEY,
	TenLop NVARCHAR(10) ,
	MaKhoi varchar(10)
);

CREATE TABLE KHOILOP
(
	MaKhoi VARCHAR(10) PRIMARY KEY,
	TenKhoi NVARCHAR(10) 
);

CREATE TABLE PHANCONG
(
	MaLop VARCHAR(10),
	MaGV VARCHAR(10),
	LoaiCongViec NVARCHAR(50),

	CONSTRAINT PK_PHANCONG PRIMARY KEY(MaLop,MaGV)
)


------------------------------TẠO KHÓA NGOẠI LIÊN KẾT CÁC BẢNG-----------------------------------

ALTER TABLE dbo.HOCSINH ADD CONSTRAINT FK_HOCSINH_LOP FOREIGN KEY(MaLop) REFERENCES dbo.LOP(MaLop)
GO

ALTER TABLE dbo.HOCSINH ADD CONSTRAINT FK_HOCSINH_DIEM FOREIGN KEY(MaHS) REFERENCES dbo.LOP(MaHS)
GO

ALTER TABLE dbo.MONHOC ADD CONSTRAINT FK_MONHOC_DIEM FOREIGN KEY (MaMH) REFERENCES dbo.DIEM(MaMH)
GO

ALTER TABLE dbo.GIAOVIEN ADD CONSTRAINT FK_GIAOVIEN_MONHOC FOREIGN KEY(MaMH) REFERENCES dbo.MONHOC(MaMH)
GO

ALTER TABLE dbo.PHANCONG ADD CONSTRAINT FK_PHANCONG_GIAOVIEN FOREIGN KEY (MaGV) REFERENCES dbo.GIAOVIEN(MaGV)
GO

ALTER TABLE dbo.PHANCONG ADD CONSTRAINT FK_PHANCONG_LOPFOREIGN FOREIGN KEY(MaLop) REFERENCES dbo.LOP(MaLop)
GO

ALTER TABLE dbo.LOP ADD CONSTRAINT FK_LOP_KHOILOP FOREIGN KEY(MaKhoi) REFERENCES dbo.KHOILOP(MaKhoi)
GO



